device: 'cuda'
verbose: 1
buffer_size: 3000000
learning_starts: 1000
batch_size: 534
learning_rate: 0.00082
tau: 0.426
train_freq: [ 1000, 'step' ]
gamma: 0.97
ent_coef: 'auto_0.6'
policy_kwargs:
  activation_fn: 'ELU'
  net_arch:
    pi: [ 128, 128, 128 ]
    qf: [ 128, 128, 128 ]