device: 'cpu'
verbose: 2
buffer_size: 10000000
learning_starts: 1000
batch_size: 155
learning_rate: 0.0002
tau: 0.62
train_freq: [ 2, 'step' ]
gamma: 0.98
ent_coef: 'auto'
policy_kwargs:
  activation_fn: 'ELU'
  net_arch:
    pi: [ 128, 128, 128 ]
    qf: [ 128, 128, 128 ]