device: 'cpu'
verbose: 1
buffer_size: 10000000
learning_starts: 1000
batch_size: 692
learning_rate: 0.00001
tau: 0.343
train_freq: [ 2, 'step' ]
gamma: 0.958
ent_coef: 'auto'
policy_kwargs:
  activation_fn: 'ELU'
  net_arch:
    pi: [ 128, 128, 128 ]
    qf: [ 128, 128, 128 ]